name: Flutter CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v2.2.1
        with:
          channel: 'stable'
      - name: Download Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: key.jks
          encodedString: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      - name: Create key.properties
        run: echo "${{ secrets.KEY_PROPERTIES }}" > android/key.properties
      - name: Install dependencies
        run: flutter pub get
      - name: Build APK
        run: |
          cd android
          flutter deploy
      - name: Rename APK
        run: mv build/app/outputs/flutter-apk/app-release.apk ./Meta-Vest-Sample-SNAPSHOT.apk
      - name: Archive APK
        uses: actions/upload-artifact@v1
        with:
          name: android-build
          path: ./Meta-Vest-Sample-SNAPSHOT.apk
  build_ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v1.4.0
        with:
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Build IOS
        run: flutter build ios --release --no-codesign
